# Generated by Django 4.1.4 on 2023-01-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEflix_APP', '0002_register_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_club',
            name='id',
        ),
        migrations.AlterField(
            model_name='register_club',
            name='club_contact_land_num',
            field=models.IntegerField(verbose_name='landline nunmber'),
        ),
        migrations.AlterField(
            model_name='register_club',
            name='club_contact_mobile_num',
            field=models.IntegerField(verbose_name='Mobile number'),
        ),
        migrations.AlterField(
            model_name='register_club',
            name='club_rep_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
