# Generated by Django 4.1.4 on 2023-01-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEflix_APP', '0003_remove_register_club_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_club',
            name='club_contact_land_num',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='register_club',
            name='club_contact_mobile_num',
            field=models.CharField(max_length=7),
        ),
    ]
