# Generated by Django 4.1.4 on 2023-01-05 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UWEflix_APP', '0004_alter_register_club_club_contact_land_num_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogMessage',
        ),
    ]
