# Generated by Django 4.1.4 on 2023-01-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEflix_APP', '0005_delete_logmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_club',
            name='club_address_city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='register_club',
            name='club_address_postcode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='register_club',
            name='club_address_street',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='register_club',
            name='club_address_street_num',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='register_club',
            name='club_contact_land_num',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='register_club',
            name='club_contact_mobile_num',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='register_club',
            name='club_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='register_club',
            name='club_rep_fname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='register_club',
            name='club_rep_lname',
            field=models.CharField(max_length=50),
        ),
    ]
